apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-releases.fullname" . }}
  labels:
    {{- include "github-releases.labels" . | nindent 4 }}
type: Opaque
data:
  github-token: {{ .Values.githubToken | b64enc | quote }}
