apiVersion: v2
name: github-releases
description: A Helm chart for GitHub Releases service
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "12.5.6"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
